name = input("What is your name? ")
color = input("What is your favorite color?")
place = input("Where are you from?")
print("Hi", name)
print("I think its cool to know that your favorite color is", color)
print("Thats really cool you are from", place)           
input("Press enter to exit")
