first = input("What is your first name? ")
last = input("What is your last name? ")
print(f"Your name is {last}, {first} {last}. ")
print(f"It's nice to meet you {last}, {first} {last}. ")
input("Press ENTER to Exit")
